[tool.poetry]
name = "poetry-template"
version = "0.1.0"
description = ""
authors = ["Akagi201 <akagi201@gmail.com>"]
readme = "README.md"
packages = [{include = "poetry_template", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
black = "^23.3.0"
pytest = "^7.3.1"
jupyterlab = {version = "^3.6.3", optional = true}
ruff = "^0.0.265"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
